// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file_management/file_management.proto

package file_management

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request for file download and delete operations.
type FileRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68245b7dcfc510e, []int{0}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

// Request for file renaming operation.
type RenameRequest struct {
	OldFileName          string   `protobuf:"bytes,1,opt,name=old_file_name,json=oldFileName,proto3" json:"old_file_name,omitempty"`
	NewFileName          string   `protobuf:"bytes,2,opt,name=new_file_name,json=newFileName,proto3" json:"new_file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameRequest) Reset()         { *m = RenameRequest{} }
func (m *RenameRequest) String() string { return proto.CompactTextString(m) }
func (*RenameRequest) ProtoMessage()    {}
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68245b7dcfc510e, []int{1}
}

func (m *RenameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameRequest.Unmarshal(m, b)
}
func (m *RenameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameRequest.Marshal(b, m, deterministic)
}
func (m *RenameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameRequest.Merge(m, src)
}
func (m *RenameRequest) XXX_Size() int {
	return xxx_messageInfo_RenameRequest.Size(m)
}
func (m *RenameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenameRequest proto.InternalMessageInfo

func (m *RenameRequest) GetOldFileName() string {
	if m != nil {
		return m.OldFileName
	}
	return ""
}

func (m *RenameRequest) GetNewFileName() string {
	if m != nil {
		return m.NewFileName
	}
	return ""
}

// Request for file upload operation.
type FileChunk struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68245b7dcfc510e, []int{2}
}

func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunk.Unmarshal(m, b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
}
func (m *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(m, src)
}
func (m *FileChunk) XXX_Size() int {
	return xxx_messageInfo_FileChunk.Size(m)
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Response for all file operations.
type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68245b7dcfc510e, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Message encapsulating the file name.
type FileNameMessage struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileNameMessage) Reset()         { *m = FileNameMessage{} }
func (m *FileNameMessage) String() string { return proto.CompactTextString(m) }
func (*FileNameMessage) ProtoMessage()    {}
func (*FileNameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68245b7dcfc510e, []int{4}
}

func (m *FileNameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileNameMessage.Unmarshal(m, b)
}
func (m *FileNameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileNameMessage.Marshal(b, m, deterministic)
}
func (m *FileNameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileNameMessage.Merge(m, src)
}
func (m *FileNameMessage) XXX_Size() int {
	return xxx_messageInfo_FileNameMessage.Size(m)
}
func (m *FileNameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FileNameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FileNameMessage proto.InternalMessageInfo

func (m *FileNameMessage) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68245b7dcfc510e, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type FileList struct {
	Files                []*FileInfo `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FileList) Reset()         { *m = FileList{} }
func (m *FileList) String() string { return proto.CompactTextString(m) }
func (*FileList) ProtoMessage()    {}
func (*FileList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68245b7dcfc510e, []int{6}
}

func (m *FileList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileList.Unmarshal(m, b)
}
func (m *FileList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileList.Marshal(b, m, deterministic)
}
func (m *FileList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileList.Merge(m, src)
}
func (m *FileList) XXX_Size() int {
	return xxx_messageInfo_FileList.Size(m)
}
func (m *FileList) XXX_DiscardUnknown() {
	xxx_messageInfo_FileList.DiscardUnknown(m)
}

var xxx_messageInfo_FileList proto.InternalMessageInfo

func (m *FileList) GetFiles() []*FileInfo {
	if m != nil {
		return m.Files
	}
	return nil
}

type FileInfo struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ModificationTime     int64    `protobuf:"varint,2,opt,name=modification_time,json=modificationTime,proto3" json:"modification_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68245b7dcfc510e, []int{7}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileInfo) GetModificationTime() int64 {
	if m != nil {
		return m.ModificationTime
	}
	return 0
}

func init() {
	proto.RegisterType((*FileRequest)(nil), "FileRequest")
	proto.RegisterType((*RenameRequest)(nil), "RenameRequest")
	proto.RegisterType((*FileChunk)(nil), "FileChunk")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*FileNameMessage)(nil), "FileNameMessage")
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*FileList)(nil), "FileList")
	proto.RegisterType((*FileInfo)(nil), "FileInfo")
}

func init() {
	proto.RegisterFile("file_management/file_management.proto", fileDescriptor_d68245b7dcfc510e)
}

var fileDescriptor_d68245b7dcfc510e = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdf, 0x4e, 0x22, 0x31,
	0x14, 0xc6, 0x33, 0xcb, 0xf2, 0x67, 0x0e, 0xb0, 0xbb, 0x74, 0x6f, 0x08, 0x26, 0x42, 0x1a, 0x89,
	0x04, 0x92, 0x6a, 0xf0, 0x0d, 0x14, 0x49, 0x4c, 0xd4, 0x8b, 0x11, 0x63, 0xe2, 0x0d, 0xa9, 0xcc,
	0x01, 0x1b, 0xa7, 0xed, 0x48, 0x8b, 0xc4, 0xb7, 0xf4, 0x91, 0x4c, 0x67, 0x18, 0x1c, 0x89, 0xe1,
	0xae, 0xfd, 0xce, 0xef, 0x7c, 0x4d, 0xbf, 0x73, 0xa0, 0x3b, 0x17, 0x11, 0x4e, 0x25, 0x57, 0x7c,
	0x81, 0x12, 0x95, 0x3d, 0xd9, 0xb9, 0xb3, 0x78, 0xa9, 0xad, 0xa6, 0x7d, 0xa8, 0x8e, 0x45, 0x84,
	0x01, 0xbe, 0xae, 0xd0, 0x58, 0x72, 0x00, 0x7e, 0xc2, 0x29, 0x2e, 0xb1, 0xe9, 0x75, 0xbc, 0x9e,
	0x1f, 0x54, 0x9c, 0x70, 0xcb, 0x25, 0xd2, 0x07, 0xa8, 0x07, 0xe8, 0x2a, 0x19, 0x4d, 0xa1, 0xae,
	0xa3, 0x70, 0xba, 0xdb, 0x51, 0xd5, 0x51, 0x38, 0xde, 0x34, 0x39, 0x46, 0xe1, 0x3a, 0xc7, 0xfc,
	0x4a, 0x19, 0x85, 0xeb, 0x8c, 0xa1, 0x6d, 0xf0, 0xdd, 0xf9, 0xe2, 0x79, 0xa5, 0x5e, 0x08, 0x81,
	0xdf, 0x21, 0xb7, 0x3c, 0xf1, 0xaa, 0x05, 0xc9, 0x99, 0x1e, 0x41, 0x25, 0x40, 0x13, 0x6b, 0x65,
	0x90, 0x34, 0xa1, 0x2c, 0xd1, 0x18, 0xbe, 0xc8, 0x9e, 0xcb, 0xae, 0x94, 0xc1, 0xdf, 0xcc, 0xf2,
	0x26, 0x95, 0xf6, 0xff, 0xa7, 0x0c, 0xc5, 0x4b, 0x19, 0xdb, 0x77, 0x3a, 0x80, 0x8a, 0x6b, 0xbc,
	0x16, 0xc6, 0x92, 0x36, 0x14, 0x1d, 0x60, 0x9a, 0x5e, 0xa7, 0xd0, 0xab, 0x0e, 0x7d, 0xe6, 0x2a,
	0x57, 0x6a, 0xae, 0x83, 0x54, 0xa7, 0x93, 0x14, 0x76, 0xd2, 0x5e, 0x7b, 0x32, 0x80, 0x86, 0xd4,
	0xa1, 0x98, 0x8b, 0x19, 0xb7, 0x42, 0xab, 0xa9, 0x15, 0x9b, 0xdf, 0x17, 0x82, 0x7f, 0xf9, 0xc2,
	0x44, 0x48, 0x1c, 0x7e, 0x78, 0xe9, 0x20, 0xee, 0x70, 0xf9, 0x26, 0x66, 0x48, 0xba, 0x00, 0xf7,
	0x71, 0xa4, 0x79, 0x12, 0x24, 0x01, 0xb6, 0xcd, 0xa7, 0xe5, 0xb3, 0x2c, 0x8a, 0x9e, 0x47, 0xfa,
	0x50, 0x1b, 0xe9, 0xb5, 0xda, 0x82, 0x35, 0x96, 0x9b, 0x66, 0x2b, 0xd7, 0x76, 0xea, 0x39, 0xcb,
	0x11, 0x46, 0x68, 0xf1, 0x07, 0xf2, 0xcb, 0x94, 0x1c, 0x03, 0xa4, 0x53, 0x4e, 0xb0, 0x3f, 0xec,
	0xdb, 0xc8, 0xf3, 0xe0, 0x21, 0xf8, 0x2e, 0x31, 0x87, 0x19, 0x52, 0x62, 0x49, 0x94, 0xad, 0x34,
	0x2f, 0xa7, 0x9f, 0xff, 0x7f, 0x6c, 0xb0, 0xdd, 0xad, 0x7b, 0x2a, 0x25, 0x6b, 0x77, 0xf6, 0x19,
	0x00, 0x00, 0xff, 0xff, 0x45, 0xc4, 0xe3, 0xf9, 0x9f, 0x02, 0x00, 0x00,
}
